# Generated by Django 5.0.2 on 2024-03-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_header_onglet_5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(max_length=200)),
                ('sous_slogan', models.CharField(max_length=200)),
                ('Bouton_page1', models.CharField(max_length=200)),
                ('image_1_accueil', models.ImageField(upload_to='media/acceuil/')),
                ('text_presentation', models.CharField(max_length=200)),
                ('sous_text_presentation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/presentation/')),
                ('title_presentation', models.CharField(max_length=200)),
                ('text_presentation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Valeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/valeur/')),
                ('title_valeur', models.CharField(max_length=200)),
                ('text_valeur', models.CharField(max_length=200)),
            ],
        ),
    ]
