# Generated by Django 5.0.2 on 2024-03-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_accueil_presentation_valeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carasteristique1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/carasteristique/')),
                ('text_domaine1', models.CharField(max_length=200)),
                ('text_domaine2', models.CharField(max_length=200)),
                ('text_domaine3', models.CharField(max_length=200)),
                ('text_domaine4', models.CharField(max_length=200)),
                ('text_domaine5', models.CharField(max_length=200)),
                ('text_domaine6', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='accueil',
            name='image',
            field=models.ImageField(default=False, upload_to='media/carasteristique/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accueil',
            name='sous_text_carasteristique1',
            field=models.CharField(default=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accueil',
            name='sous_text_carasteristique2',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accueil',
            name='sous_text_carasteristique3',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accueil',
            name='sous_text_valeur',
            field=models.CharField(default=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accueil',
            name='text_carasteristique',
            field=models.CharField(default='False', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accueil',
            name='text_valeur',
            field=models.CharField(default=False, max_length=200),
            preserve_default=False,
        ),
    ]
