# Generated by Django 5.0.2 on 2024-03-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_carasteristique1_accueil_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accueil',
            old_name='image',
            new_name='image2',
        ),
        migrations.AddField(
            model_name='accueil',
            name='image3',
            field=models.ImageField(default=False, upload_to='media/carasteristique/'),
            preserve_default=False,
        ),
    ]
