# Generated by Django 5.0.2 on 2024-03-24 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_image_accueil_image2_accueil_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carasteristique1',
            name='image',
        ),
        migrations.RemoveField(
            model_name='carasteristique1',
            name='text_domaine1',
        ),
    ]
