# Generated by Django 5.0.2 on 2024-03-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_carasteristique1_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accueil',
            name='image1',
            field=models.ImageField(default=False, upload_to='media/carasteristique/'),
            preserve_default=False,
        ),
    ]
