# Generated by Django 5.0.2 on 2024-03-24 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_carasteristique1_text_domaine1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carasteristique1',
            old_name='text_domaine1',
            new_name='text_domaine',
        ),
        migrations.RemoveField(
            model_name='carasteristique1',
            name='text_domaine2',
        ),
        migrations.RemoveField(
            model_name='carasteristique1',
            name='text_domaine3',
        ),
        migrations.RemoveField(
            model_name='carasteristique1',
            name='text_domaine4',
        ),
        migrations.RemoveField(
            model_name='carasteristique1',
            name='text_domaine5',
        ),
        migrations.RemoveField(
            model_name='carasteristique1',
            name='text_domaine6',
        ),
    ]
