# Generated by Django 5.0.2 on 2024-03-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_text_domaine1_carasteristique1_text_domaine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carasteristique2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sout_text', models.TextField(max_length=200)),
                ('sous_titre1', models.CharField(max_length=200)),
                ('sous_text1', models.TextField(max_length=200)),
                ('sous_titre2', models.CharField(max_length=200)),
                ('sous_text2', models.TextField(max_length=200)),
                ('sous_titre3', models.CharField(max_length=200)),
                ('sous_text3', models.TextField(max_length=200)),
            ],
        ),
    ]
