# Generated by Django 5.0.2 on 2024-03-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_accueil_title_carasteristique2_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carasteristique2',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
