# Generated by Django 5.0.2 on 2024-03-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_carasteristique3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='accueil',
            name='sous_text_question',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accueil',
            name='text_question',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
