# Generated by Django 5.0.2 on 2024-03-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_question_accueil_sous_text_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='js1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='js2',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
