# Generated by Django 5.0.2 on 2024-03-24 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_question_js1_question_js2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='js1',
        ),
    ]
