# Generated by Django 5.0.2 on 2024-03-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_question_js1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('person_poste', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='accueil',
            name='sous_text_testimonail',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accueil',
            name='text_temstimonail',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
