# Generated by Django 5.0.2 on 2024-03-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_temoin_accueil_sous_text_testimonail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
                ('title3', models.CharField(max_length=200)),
                ('image1', models.ImageField(upload_to='media/about/')),
                ('image2', models.ImageField(upload_to='media/about/')),
                ('image3', models.ImageField(upload_to='media/about/')),
                ('title_resume', models.CharField(max_length=200)),
                ('text_resume', models.TextField()),
                ('Name_Urbain', models.CharField(max_length=200)),
                ('Email_Urbain', models.CharField(max_length=200)),
                ('Horaire', models.CharField(max_length=200)),
                ('text_domain', models.CharField(max_length=200)),
                ('sous_text_domaine', models.CharField(max_length=200)),
                ('text_partenaire', models.CharField(max_length=200)),
                ('sous_text_partenaire', models.CharField(max_length=200)),
            ],
        ),
    ]
