# Generated by Django 5.0.2 on 2024-03-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='sous_text_blog',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='text_blog',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
