# Generated by Django 5.0.2 on 2024-03-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_about_sous_text_blog_about_text_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
                ('title3', models.CharField(max_length=200)),
                ('text_equipe', models.CharField(max_length=200)),
                ('sous_text_equipe', models.CharField(max_length=200)),
                ('sous_text_equipe1', models.CharField(max_length=200)),
                ('text_projet', models.CharField(max_length=200)),
                ('sous_text_projet', models.CharField(max_length=200)),
            ],
        ),
    ]
