# Generated by Django 5.0.2 on 2024-03-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_offre'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='color',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
