# Generated by Django 5.0.2 on 2024-03-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_offre_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='sous_text_equipe2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
