# Generated by Django 5.0.2 on 2024-03-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_postemembre_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='Methode1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('meth_1', models.CharField(max_length=200)),
                ('text_meth_1', models.CharField(max_length=200)),
                ('meth_2', models.CharField(max_length=200)),
                ('text_meth_2', models.CharField(max_length=200)),
                ('meth_3', models.CharField(max_length=200)),
                ('text_meth_3', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/team/')),
            ],
        ),
        migrations.CreateModel(
            name='Methode2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('meth_1', models.CharField(max_length=200)),
                ('text_meth_1', models.CharField(max_length=200)),
                ('meth_2', models.CharField(max_length=200)),
                ('text_meth_2', models.CharField(max_length=200)),
                ('meth_3', models.CharField(max_length=200)),
                ('text_meth_3', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/team/')),
            ],
        ),
        migrations.CreateModel(
            name='Methode3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('meth_1', models.CharField(max_length=200)),
                ('text_meth_1', models.CharField(max_length=200)),
                ('meth_2', models.CharField(max_length=200)),
                ('text_meth_2', models.CharField(max_length=200)),
                ('meth_3', models.CharField(max_length=200)),
                ('text_meth_3', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/team/')),
            ],
        ),
    ]
