# Generated by Django 5.0.2 on 2024-03-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_cadre_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadre',
            name='image',
            field=models.ImageField(upload_to='media/team/cadre/'),
        ),
    ]
