# Generated by Django 5.0.2 on 2024-03-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_card_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Contact',
        ),
    ]
