# Generated by Django 5.0.2 on 2024-03-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_rename_info_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='map',
        ),
        migrations.AddField(
            model_name='contact',
            name='map_localisation',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
