# Generated by Django 5.0.2 on 2024-03-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_contact_map_contact_map_localisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/projets/')),
                ('title', models.CharField(max_length=200)),
                ('display', models.CharField(max_length=100)),
                ('js1', models.CharField(max_length=100)),
                ('js2', models.CharField(max_length=100)),
            ],
        ),
    ]
