# Generated by Django 5.0.2 on 2024-03-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_projets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projets',
            new_name='Projet',
        ),
    ]
