# Generated by Django 5.0.2 on 2024-03-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_rename_projets_projet'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_abonne', models.CharField(max_length=200)),
                ('sous_text_abonne', models.CharField(max_length=200)),
                ('button_abonne', models.CharField(max_length=200)),
                ('service', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('crypt', models.CharField(max_length=200)),
                ('design', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200)),
            ],
        ),
    ]
