# Generated by Django 5.0.2 on 2024-03-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_footer_lien_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='lien',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
