# Generated by Django 5.0.2 on 2024-03-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_footer_lien_footer_name_urbain_footer_text_lien_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu1', models.CharField(max_length=200)),
                ('lieu2', models.CharField(max_length=200)),
                ('lieu3', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('contact2', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('email2', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
