# Generated by Django 5.0.2 on 2024-03-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_home', models.ImageField(upload_to='media/section/')),
                ('image_service', models.ImageField(upload_to='media/section/')),
                ('image_footer', models.ImageField(upload_to='media/section/')),
                ('image_equipe', models.ImageField(upload_to='media/section/')),
            ],
        ),
    ]
