# Generated by Django 5.0.2 on 2024-04-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carasteristique2',
            name='sous_text1_1',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='carasteristique2',
            name='sous_text1_2',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='carasteristique2',
            name='sous_text1_3',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='carasteristique2',
            name='sous_text2_1',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='carasteristique2',
            name='sous_text2_2',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='carasteristique2',
            name='sous_text2_3',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='carasteristique2',
            name='sous_text3_1',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='carasteristique2',
            name='sous_text3_2',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='carasteristique2',
            name='sous_text3_3',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='carasteristique2',
            name='sout_text1',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='carasteristique2',
            name='sout_text2',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='carasteristique2',
            name='sout_text3',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='carasteristique3',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='js2',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='temoin',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
